-- AlterTable
ALTER TABLE "providers" ADD COLUMN     "isAutoScheduled" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "scheduling_preferences" ADD COLUMN     "equityThresholdHigh" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
ADD COLUMN     "equityThresholdLow" DOUBLE PRECISION NOT NULL DEFAULT 0.25,
ADD COLUMN     "equityThresholdMed" DOUBLE PRECISION NOT NULL DEFAULT 0.75,
ADD COLUMN     "fairnessDesirabilityWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.75,
ADD COLUMN     "fairnessHolidayWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.25,
ADD COLUMN     "fourDayWeekendWeight" DOUBLE PRECISION NOT NULL DEFAULT 8,
ADD COLUMN     "sequentialOffWeight" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN     "threeDayWeekendWeight" DOUBLE PRECISION NOT NULL DEFAULT 5;
